import enum


class Category(enum.Enum):
    GENERAL_KNOWLEDGE = '&category=9'
    ENTERTAINMENT_BOOKS = '&category=10'
    ENTERTAINMENT_FILM = '&category=11'
    ENTERTAINMENT_MUSIC = '&category=12'
    ENTERTAINMENT_MUSICALS_AND_THEATRES = '&category=13'
    ENTERTAINMENT_TELEVISION = '&category=14'
    ENTERTAINMENT_VIDEO_GAMES = '&category=15'
    ENTERTAINMENT_BOARD_GAMES = '&category=16'
    SCIENCE_AND_NATURE = '&category=17'
    SCIENCE_COMPUTERS = '&category=18'
    SCIENCE_MATHEMATICS = '&category=19'
    MYTHOLOGY = '&category=20'
    SPORTS = '&category=21'
    GEOGRAPHY = '&category=22'
    HISTORY = '&category=23'
    POLITICS = '&category=24'
    ART = '&category=25'
    CELEBRITIES = '&category=26'
    ANIMALS = '&category=27'
    VEHICLES = '&category=28'
    ENTERTAINMENT_COMICS = '&category=29'
    SCIENCE_GADGETS = '&category=30'
    ENTERTAINMENT_JAPANESE_ANIME_AND_MANGA = '&category=31'
    ENTERTAINMENT_CARTOON_AND_ANIMATIONS = '&category=32'
    ALL = ''
